name: Deploy docs to gh-pages

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          python-version: '3.7'

      - name: Install dependencies with conda
        shell: bash -l {0}
        run: |
          conda install pip 
          conda install -c conda-forge numpy scipy sympy
          conda install -c conda-forge petsc4py petsc mpi4py h5py

      - name: Install pdoc3
        shell: bash -l {0}
        run: |
          pip install pdoc3

      - name: Install (self)
        shell: bash -l {0}
        run: |
          python --version 
          rm -rf conduction/Examples
          pip install -e .
   
      - name: Build docs with pdoc
        shell: bash -l {0}
        run: |
          mkdir -p docs
          pdoc3 --config latex_math=True --html -o docs --force conduction 

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch